@baseurl = http://127.0.0.1:5000
@foreignSite = https://idfg.idaho.gov/ifwis/huntplanner/stats/

### create a user

POST {{baseurl}}/api/users/register
Accept: application/json
Content-Type: application/json

{
    "username":"gerald",
    "email":"kyle360@gmail.com",
    "password":"password1"
}

### logs in user

POST {{baseurl}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email":"kyle360@gmail.com",
    "password":"password1"
}

### tests password validation

GET {{baseurl}}/api/users/validate
Accept: application/json
Content-Type: application/json

{
    "password":"4"
}

### test harvest route

GET {{baseurl}}/api/harveststatistics/:season/:animal/:year
Accept: application/json
Content-Type: application/json

{
    "year":"2019",
    "animal":"elk",
    "season":"general"
}

### test defualt harvsetStats response

GET {{foreignSite}}