@baseurl = http://127.0.0.1:5000

### create a user

POST {{baseurl}}/api/users/register
Accept: application/json
Content-Type: application/json

{
    "username":"gerald",
    "email":"kyle360@gmail.com",
    "password":"password1"
}

### logs in user

POST {{baseurl}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email":"kyle360@gmail.com",
    "password":"password1"
}

### tests password validation

GET {{baseurl}}/api/users/validate
Accept: application/json
Content-Type: application/json

{
    "password":"4"
}
