// template object for what columns to grab
// NOTE: might eliminate these and dumb down by iterating through each table on
// client side or within osmosis.set(function(){ HERE })

const animal = {
  GeneralDeer: {
    'TakeMethod': "td[1]",
    'Unit': "td[2]",
    'Harvest': "td[3]",
    'Hunter': "td[4]",
    'SuccessRate': "td[5]",
    'Days': "td[6]",
    'Antlered': "td[7]",
    'Anterless': "td[8]",
    '4+Points': "td[9]",
    '5+Points': "td[10]",
    'Whitetail': "td[11]",
  },
  ControlledDeer: {
    'HuntNumber': "td[1]",
    'TakeMethod': "td[2]",
    'Area': "td[3]",
    'Hunter': "td[4]",
    'Harvest': "td[5]",
    'SuccessRate': "td[6]",
    'Days': "td[7]",
    'Antlered': "td[8]",
    'Antlerless': "td[9]",
    '4+Points': "td[10]",
    '5+Points': "td[11]",
    'Whitetail': "td[12]",
  },
  Lion: {
    'Unit': "td[1]",
    'Harvest': "td[2]",
    'Male': "td[3]",
    'Female': "td[4]",
  },
  Wolf: {
    'Unit': "td[1]",
    'Harvest': "td[2]",
    'Male': "td[3]",
    'Female': "td[4]",
  },
  GeneralBear: {
    'Unit': "td[1]",
    'Harvest': "td[2]",
    'Boars': "td[3]",
    'Sows': "td[4]",
    'Fall': "td[5]",
    'Spring': "td[6]",
    'Bait': "td[7]",
    'Hounds': "td[8]",
    'Incidental': "td[9]",
    'StillStalk': "td[10]",
  },
  ControlledBear: {
    'HuntNumber': "td[1]",
    'TakeMethod': "td[2]",
    'Area': "td[3]",
    'Hunters': "td[4]",
    'Harvest': "td[5]",
    'SuccessRate': "td[6]",
    'Days': "td[7]",
    'Boars': "td[8]",
    'Sows': "td[9]",
    'Fall': "td[10]",
    'Spring': "td[11]",
    'Bait': "td[12]",
  },
  Goat: {
    'HuntNumber': "td[1]",
    'TakeMethod': "td[2]",
    'Area': "td[3]",
    'Hunter': "td[4]",
    'Harvest': "td[5]",
    'SuccessRate': "td[6]",
    'Days': "td[7]",
    'Billies': "td[8]",
    'Nannies': "td[9]",
    'SixPlusPoints': "td[10]",
  },
  ControlledTurkey: {
    'Season': "td[1]",
    'HuntNumber': "td[2]",
    'TakeMethod': "td[3]",
    'Area': "td[4]",
    'Hunters': "td[5]",
    'Harvest': "td[6]",
    'SuccessRate': "td[7]",
    'Days': "td[8]",
    'Toms': "td[9]",
    'Hens': "td[10]",
    'Days/Hunter': "td[11]",
    'Birds/Day': "td[12]",
  },
  GeneralTurkey: {
    'Season': "td[1]",
    'Unit': "td[2]",
    'Harvest': "td[3]",
    'Hunter': "td[4]",
    'DaysPerHunter': "td[5]",
    'BirdsPerDay': "td[6]",
    'DaysPerBird': "td[7]",
  },
  GeneralPronghorn: {
    'TakeMethod': "td[1]",
    'Unit': "td[2]",
    'Harvest': "td[3]",
    'Hunter': "td[4]",
    'SuccessRate': "td[5]",
    'Days': "td[6]",
    'Horned': "td[7]",
    'Hornless': "td[8]",
    'AvgHornLengthInch': "td[9]",
  },
  ControlledPronghorn: {
    'HuntNumber': "td[1]",
    'TakeMethod': "td[2]",
    'Area': "td[3]",
    'Hunter': "td[5]",
    'Harvest': "td[4]",
    'SuccessRate': "td[6]",
    'Days': "td[7]",
    'Horned': "td[8]",
    'Hornless': "td[9]",
    'AvgHornLengthInch': "td[10]",
  },
  Sheep: {
    'HuntNumber': "td[1]",
    'TakeMethod': "td[2]",
    'Area': "td[3]",
    'Hunter': "td[4]",
    'Harvest': "td[5]",
    'SuccessRate': "td[6]",
    'Days': "td[7]",
    'Rams': "td[8]",
    'Ewes': "td[9]",
    'AvgHornLengthInch': "td[10]",
    'AvgHornCircumferenceInch': "td[10]",
  },
  GeneralElk: {
    'TakeMethod': "td[1]",
    'Unit': "td[2]",
    'Harvest': "td[3]",
    'Hunter': "td[4]",
    'SuccessRate': "td[5]",
    'Days': "td[6]",
    'Antlered': "td[7]",
    'Anterless': "td[8]",
    'Spike': "td[9]",
    'SixPlusPoints': "td[10]",
  },
  ControlledElk: {
    'HuntNumber': "td[2]",
    'TakeMethod': "td[1]",
    'Area': "td[3]",
    'Hunter': "td[4]",
    'Harvest': "td[5]",
    'SuccessRate': "td[6]",
    'Days': "td[7]",
    'Antlered': "td[8]",
    'Anterless': "td[9]",
    'Spike': "td[10]",
    'SixPlusPoints': "td[11]",
  },
  Moose: {
    'HuntNumber': "td[1]",
    'TakeMethod': "td[2]",
    'Area': "td[3]",
    'Hunters': "td[4]",
    'Harvest': "td[5]",
    'SuccessRate': "td[6]",
    'Days': "td[7]",
    'Bulls': "td[8]",
    'Cows': "td[9]",
    'AvgAntlerSpreadInch': "td[10]",
  },
};

module.exports = {
  animal,
}